### Configuration file used for all visualization scripts

paths:
  # general data path
  data: 'C:/Users/andri/school/bio-informatics/internship/donders/data/human_test_data'
  # path to raw psg.edf
  raw: 'pre_processing/input/raw_input'
  # path to raw hypnogram.edf
  anno: 'pre_processing/input/annotation_raw'
  # input folder
  #mat: 'D:\dilon_data\datasets\MOTORWP4_dataset\sleep-edf_channel_test_mats'
  mat: 'D:\dilon_data\mat_collection\static'
  # path to bandpower output
  bandpower: 'pre_processing/bandpower'
  # path to data visualization
  data_vis: 'visualizations/data_visualizations'
  # path to visualization
  feature_vis: 'visualizations/feature_visualization'

variables:
  # subject to use for visualization
  subject: "S40_2"
  upper_mask_freq: 50
  lower_mask_freq: 1
  # sampling frequency
  fs: 250
  # epoch (s)
  epoch: 10
  # sleep ids and corresponding labels
  sleep_labels: {0: 'Wake', 1: 'N1', 2: 'N2', 3: 'N3', 4: 'REM', 5: "Movement", 6: "Unknown"}
  # category of feature visualization
  category: 'new_features'
  # channels to use
  channels: ["Fpz-Cz", "Pz-Oz", "horizontal", "submental"]
  # amount of time to save before and after first and last sleep
  wake_time: 1800