name: u-sleep
channels:
  - defaults
  - conda-forge
dependencies:
  - conda>=4.10.3
  - python==3.9
  - pip>=21.2.4
  - setuptools>=52.0.0
  - tk>=8.6.10
  - wheel>=0.37.0
  - numpy==1.26.4
  - tables==3.8
  - tensorflow==2.11.1
  - tfa-nightly==0.23.0.dev20240415222534
