"""
Feature statistics and visualization pipeline for mcRBM feature selection.

This script reads an HDF5 file generated by the Jalmar hdf5 module, computes
statistics that reflect how informative each feature is for sleep-stage
separation, and exports plots/tables for feature set decisions.
"""

from __future__ import annotations

import argparse
import csv
import os
import warnings
from dataclasses import dataclass
from typing import Dict, List, Sequence

import h5py
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import f_oneway, kruskal, kurtosis, skew
from sklearn.decomposition import PCA
from sklearn.feature_selection import mutual_info_classif
from sklearn.preprocessing import StandardScaler


NEAR_CONSTANT_STD = 1e-12


STAGE_NAMES = {
	0: "Awake",
	1: "N1",
	2: "N2",
	3: "N3",
	4: "REM",
	5: "Movement/Artifact",
	6: "Unknown/Uncertain",
}


@dataclass
class LoadedData:
	features: np.ndarray
	scores: np.ndarray
	feature_names: List[str]
	subjects: np.ndarray


@dataclass
class SubjectData:
	subject: str
	features: np.ndarray
	scores: np.ndarray


def _parse_feature_names(description_attr: object, n_features: int) -> List[str]:
	if description_attr is None:
		return [f"Feature_{i + 1}" for i in range(n_features)]

	if isinstance(description_attr, bytes):
		description_attr = description_attr.decode("utf-8", errors="ignore")

	names = [part.strip() for part in str(description_attr).split(",") if part.strip()]
	if len(names) != n_features:
		return [f"Feature_{i + 1}" for i in range(n_features)]
	return names


def load_hdf5_features(hdf5_path: str, include_artifacts: bool = False) -> LoadedData:
	features_all: List[np.ndarray] = []
	scores_all: List[np.ndarray] = []
	subjects_all: List[np.ndarray] = []
	feature_names: List[str] | None = None

	with h5py.File(hdf5_path, "r") as h5f:
		for subject in h5f.keys():
			group = h5f[subject]
			if "features" not in group or "scores" not in group:
				continue

			features = np.asarray(group["features"][:], dtype=np.float64)
			scores = np.asarray(group["scores"][:], dtype=np.int32)

			min_len = min(len(features), len(scores))
			features = features[:min_len]
			scores = scores[:min_len]

			if not include_artifacts:
				mask = scores != 5
				features = features[mask]
				scores = scores[mask]

			if features.size == 0:
				continue

			if feature_names is None:
				description = group.attrs.get("description_features")
				feature_names = _parse_feature_names(description, features.shape[1])

			features_all.append(features)
			scores_all.append(scores)
			subjects_all.append(np.full(shape=len(scores), fill_value=subject, dtype=object))

	if not features_all:
		raise ValueError("No valid feature/scores data found in the HDF5 file.")

	return LoadedData(
		features=np.vstack(features_all),
		scores=np.concatenate(scores_all),
		feature_names=feature_names or [f"Feature_{i + 1}" for i in range(features_all[0].shape[1])],
		subjects=np.concatenate(subjects_all),
	)


def load_hdf5_subject_data(
	hdf5_path: str,
	include_artifacts: bool = False,
) -> tuple[List[SubjectData], List[str]]:
	"""Load per-subject feature and score sequences from HDF5."""
	subject_rows: List[SubjectData] = []
	feature_names: List[str] | None = None

	with h5py.File(hdf5_path, "r") as h5f:
		for subject in h5f.keys():
			group = h5f[subject]
			if "features" not in group or "scores" not in group:
				continue

			features = np.asarray(group["features"][:], dtype=np.float64)
			scores = np.asarray(group["scores"][:], dtype=np.int32)

			min_len = min(len(features), len(scores))
			features = features[:min_len]
			scores = scores[:min_len]

			if not include_artifacts:
				mask = scores != 5
				features = features[mask]
				scores = scores[mask]

			if features.size == 0:
				continue

			if feature_names is None:
				description = group.attrs.get("description_features")
				feature_names = _parse_feature_names(description, features.shape[1])

			subject_rows.append(SubjectData(subject=str(subject), features=features, scores=scores))

	if not subject_rows:
		raise ValueError("No per-subject data found in HDF5.")

	if feature_names is None:
		feature_names = [f"Feature_{i + 1}" for i in range(subject_rows[0].features.shape[1])]

	return subject_rows, feature_names


def _safe_stats(x: np.ndarray) -> Dict[str, float]:
	valid = x[np.isfinite(x)]
	if valid.size == 0:
		return {
			"n": 0,
			"mean": np.nan,
			"std": np.nan,
			"median": np.nan,
			"q25": np.nan,
			"q75": np.nan,
			"iqr": np.nan,
			"min": np.nan,
			"max": np.nan,
			"skew": np.nan,
			"kurtosis": np.nan,
			"outlier_pct": np.nan,
		}

	q25, q75 = np.percentile(valid, [25, 75])
	iqr = q75 - q25
	lo = q25 - 1.5 * iqr
	hi = q75 + 1.5 * iqr
	outlier_pct = float(np.mean((valid < lo) | (valid > hi)) * 100.0)
	std_val = float(np.std(valid, ddof=1)) if valid.size > 1 else 0.0
	is_constant = bool(np.nanmax(valid) - np.nanmin(valid) <= NEAR_CONSTANT_STD)

	if is_constant:
		skew_val = np.nan
		kurtosis_val = np.nan
	else:
		with warnings.catch_warnings():
			warnings.simplefilter("ignore", RuntimeWarning)
			skew_val = float(skew(valid, bias=False)) if valid.size > 2 else np.nan
			kurtosis_val = float(kurtosis(valid, bias=False)) if valid.size > 3 else np.nan

	return {
		"n": float(valid.size),
		"mean": float(np.mean(valid)),
		"std": std_val,
		"median": float(np.median(valid)),
		"q25": float(q25),
		"q75": float(q75),
		"iqr": float(iqr),
		"min": float(np.min(valid)),
		"max": float(np.max(valid)),
		"skew": skew_val,
		"kurtosis": kurtosis_val,
		"is_constant": int(is_constant),
		"outlier_pct": outlier_pct,
	}


def feature_basic_statistics(features: np.ndarray, feature_names: Sequence[str]) -> List[Dict[str, float]]:
	rows: List[Dict[str, float]] = []
	for idx, fname in enumerate(feature_names):
		stats_row = _safe_stats(features[:, idx])
		stats_row["feature"] = fname
		rows.append(stats_row)
	return rows


def feature_stage_statistics(
	features: np.ndarray,
	scores: np.ndarray,
	feature_names: Sequence[str],
) -> List[Dict[str, float]]:
	rows: List[Dict[str, float]] = []
	unique_stages = sorted(int(s) for s in np.unique(scores))

	for idx, fname in enumerate(feature_names):
		x = features[:, idx]
		for stage in unique_stages:
			stage_values = x[scores == stage]
			stage_stats = _safe_stats(stage_values)
			stage_stats["feature"] = fname
			stage_stats["stage"] = stage
			stage_stats["stage_name"] = STAGE_NAMES.get(stage, f"Stage_{stage}")
			rows.append(stage_stats)

	return rows


def _fisher_score_per_feature(x: np.ndarray, y: np.ndarray, classes: np.ndarray) -> float:
	global_mean = np.mean(x)
	numerator = 0.0
	denominator = 0.0

	for c in classes:
		xc = x[y == c]
		if xc.size == 0:
			continue
		mu_c = np.mean(xc)
		var_c = np.var(xc, ddof=1) if xc.size > 1 else 0.0
		numerator += xc.size * (mu_c - global_mean) ** 2
		denominator += xc.size * var_c

	return float(numerator / (denominator + 1e-12))


def _eta_squared(x: np.ndarray, y: np.ndarray, classes: np.ndarray) -> float:
	grand_mean = np.mean(x)
	ss_total = np.sum((x - grand_mean) ** 2)
	ss_between = 0.0

	for c in classes:
		xc = x[y == c]
		if xc.size == 0:
			continue
		ss_between += xc.size * (np.mean(xc) - grand_mean) ** 2

	if ss_total <= 0:
		return np.nan
	return float(ss_between / ss_total)


def discriminative_feature_metrics(
	features: np.ndarray,
	scores: np.ndarray,
	feature_names: Sequence[str],
	random_state: int = 42,
) -> List[Dict[str, float]]:
	y = np.asarray(scores)
	classes = np.unique(y)
	mi = np.zeros(features.shape[1], dtype=float)
	std_per_feature = np.nanstd(features, axis=0)
	variable_mask = std_per_feature > NEAR_CONSTANT_STD
	if np.any(variable_mask):
		mi_var = mutual_info_classif(
			features[:, variable_mask],
			y,
			discrete_features=False,
			random_state=random_state,
		)
		mi[variable_mask] = mi_var

	rows: List[Dict[str, float]] = []
	for i, fname in enumerate(feature_names):
		x = features[:, i]
		is_constant = bool(np.nanmax(x) - np.nanmin(x) <= NEAR_CONSTANT_STD)
		grouped = [x[y == c] for c in classes if np.sum(y == c) > 1]

		if len(grouped) >= 2 and not is_constant:
			try:
				with warnings.catch_warnings():
					warnings.simplefilter("ignore")
					f_stat, anova_p = f_oneway(*grouped)
			except Exception:
				f_stat, anova_p = np.nan, np.nan

			try:
				with warnings.catch_warnings():
					warnings.simplefilter("ignore")
					k_stat, kruskal_p = kruskal(*grouped)
			except Exception:
				k_stat, kruskal_p = np.nan, np.nan
		else:
			f_stat, anova_p, k_stat, kruskal_p = np.nan, np.nan, np.nan, np.nan

		fisher = _fisher_score_per_feature(x, y, classes)
		eta2 = _eta_squared(x, y, classes)

		rows.append(
			{
				"feature": fname,
				"mutual_info": float(mi[i]),
				"fisher_score": fisher,
				"eta_squared": eta2,
				"is_constant": int(is_constant),
				"anova_f": float(f_stat) if np.isfinite(f_stat) else np.nan,
				"anova_p": float(anova_p) if np.isfinite(anova_p) else np.nan,
				"kruskal_h": float(k_stat) if np.isfinite(k_stat) else np.nan,
				"kruskal_p": float(kruskal_p) if np.isfinite(kruskal_p) else np.nan,
			}
		)

	return rows


def _minmax(x: np.ndarray) -> np.ndarray:
	x = np.asarray(x, dtype=float)
	xmin = np.nanmin(x)
	xmax = np.nanmax(x)
	if not np.isfinite(xmin) or not np.isfinite(xmax) or np.isclose(xmin, xmax):
		return np.zeros_like(x)
	return (x - xmin) / (xmax - xmin)


def rank_features(metric_rows: List[Dict[str, float]]) -> List[Dict[str, float]]:
	mi = np.array([row["mutual_info"] for row in metric_rows], dtype=float)
	fisher = np.array([row["fisher_score"] for row in metric_rows], dtype=float)
	eta2 = np.array([row["eta_squared"] for row in metric_rows], dtype=float)
	kruskal_p = np.array([row["kruskal_p"] for row in metric_rows], dtype=float)

	with np.errstate(divide="ignore"):
		neg_log_kruskal_p = -np.log10(np.clip(kruskal_p, 1e-300, 1.0))

	score = (
		0.35 * _minmax(mi)
		+ 0.30 * _minmax(fisher)
		+ 0.25 * _minmax(eta2)
		+ 0.10 * _minmax(neg_log_kruskal_p)
	)

	ranked = []
	order = np.argsort(-score)
	for rank_idx, idx in enumerate(order, start=1):
		row = dict(metric_rows[idx])
		row["selection_score"] = float(score[idx])
		row["rank"] = rank_idx
		ranked.append(row)
	return ranked


def stage_specificity_metrics(
	features: np.ndarray,
	scores: np.ndarray,
	feature_names: Sequence[str],
) -> List[Dict[str, float]]:
	"""Compute stage-specificity metrics per feature.

	For each feature, estimate how specifically it separates one stage
	from all other stages using one-vs-rest standardized effect sizes.
	"""
	y = np.asarray(scores, dtype=int)
	classes = np.unique(y)
	rows: List[Dict[str, float]] = []

	for i, fname in enumerate(feature_names):
		x = np.asarray(features[:, i], dtype=float)
		valid = np.isfinite(x)
		x = x[valid]
		yv = y[valid]

		if x.size == 0:
			rows.append(
				{
					"feature": fname,
					"most_specific_stage": -1,
					"most_specific_stage_name": "Unknown",
					"max_one_vs_rest_effect": np.nan,
					"effect_margin": np.nan,
					"stage_mean_concentration": np.nan,
				}
			)
			continue

		effects = []
		stage_means = []
		global_mean = float(np.mean(x))

		for c in classes:
			xc = x[yv == c]
			xr = x[yv != c]
			if xc.size == 0 or xr.size == 0:
				effects.append(np.nan)
				stage_means.append(np.nan)
				continue

			mu_c = float(np.mean(xc))
			mu_r = float(np.mean(xr))
			var_c = float(np.var(xc, ddof=1)) if xc.size > 1 else 0.0
			var_r = float(np.var(xr, ddof=1)) if xr.size > 1 else 0.0
			pooled_sd = float(np.sqrt((var_c + var_r) / 2.0))
			effect = abs(mu_c - mu_r) / (pooled_sd + 1e-12)
			effects.append(effect)
			stage_means.append(mu_c)

		effects_arr = np.asarray(effects, dtype=float)
		stage_means_arr = np.asarray(stage_means, dtype=float)

		if np.any(np.isfinite(effects_arr)):
			best_idx = int(np.nanargmax(effects_arr))
			max_effect = float(effects_arr[best_idx])
			sorted_effects = np.sort(effects_arr[np.isfinite(effects_arr)])
			second_best = float(sorted_effects[-2]) if sorted_effects.size >= 2 else 0.0
			effect_margin = float(max_effect - second_best)
			best_stage = int(classes[best_idx])
		else:
			max_effect = np.nan
			effect_margin = np.nan
			best_stage = -1

		# Concentration: how much one stage mean dominates the feature profile.
		if np.any(np.isfinite(stage_means_arr)):
			dev = np.abs(stage_means_arr - global_mean)
			dev = np.where(np.isfinite(dev), dev, 0.0)
			if np.sum(dev) <= 0:
				concentration = 0.0
			else:
				p = dev / np.sum(dev)
				k = max(2, p.size)
				entropy = -np.sum(p * np.log(np.clip(p, 1e-12, 1.0)))
				concentration = float(1.0 - entropy / np.log(k))
		else:
			concentration = np.nan

		rows.append(
			{
				"feature": fname,
				"most_specific_stage": best_stage,
				"most_specific_stage_name": STAGE_NAMES.get(best_stage, f"Stage_{best_stage}"),
				"max_one_vs_rest_effect": max_effect,
				"effect_margin": effect_margin,
				"stage_mean_concentration": concentration,
			}
		)

	return rows


def rank_features_by_stage_specificity(
	stage_rows: List[Dict[str, float]],
) -> List[Dict[str, float]]:
	"""Rank features by stage specificity.

	Weighted score emphasizes strong one-vs-rest effect and uniqueness
	of that effect to a single stage.
	"""
	max_effect = np.array([row["max_one_vs_rest_effect"] for row in stage_rows], dtype=float)
	margin = np.array([row["effect_margin"] for row in stage_rows], dtype=float)
	concentration = np.array([row["stage_mean_concentration"] for row in stage_rows], dtype=float)

	# Replace NaN with 0 before min-max scaling to keep ranking stable.
	max_effect = np.where(np.isfinite(max_effect), max_effect, 0.0)
	margin = np.where(np.isfinite(margin), margin, 0.0)
	concentration = np.where(np.isfinite(concentration), concentration, 0.0)

	stage_specificity_score = (
		0.50 * _minmax(max_effect)
		+ 0.30 * _minmax(margin)
		+ 0.20 * _minmax(concentration)
	)

	ranked = []
	order = np.argsort(-stage_specificity_score)
	for rank_idx, idx in enumerate(order, start=1):
		row = dict(stage_rows[idx])
		row["stage_specificity_score"] = float(stage_specificity_score[idx])
		row["rank"] = rank_idx
		ranked.append(row)
	return ranked


def _interval_metrics(interval_mask: np.ndarray, stage_mask: np.ndarray) -> tuple[float, float, float, float]:
	"""Return (coverage, precision, lift, distinctiveness_index)."""
	stage_total = int(np.sum(stage_mask))
	inside_total = int(np.sum(interval_mask))
	inside_stage = int(np.sum(interval_mask & stage_mask))
	n_total = max(1, len(stage_mask))

	coverage = inside_stage / stage_total if stage_total > 0 else 0.0
	precision = inside_stage / inside_total if inside_total > 0 else 0.0
	base_rate = stage_total / n_total
	lift = precision / (base_rate + 1e-12)
	distinctiveness = coverage * max(0.0, lift - 1.0)
	return float(coverage), float(precision), float(lift), float(distinctiveness)


def stage_distinctive_feature_intervals(
	features: np.ndarray,
	scores: np.ndarray,
	feature_names: Sequence[str],
	interval_q_low: float = 0.20,
	interval_q_high: float = 0.80,
) -> List[Dict[str, float]]:
	"""Find stage-indicative value intervals for each single feature.

	For each stage-feature pair, the stage interval is estimated by the
	[interval_q_low, interval_q_high] quantiles of that feature within the stage.
	"""
	rows: List[Dict[str, float]] = []
	unique_stages = sorted(int(s) for s in np.unique(scores))

	for stage in unique_stages:
		stage_mask = np.asarray(scores == stage)
		for i, fname in enumerate(feature_names):
			x = np.asarray(features[:, i], dtype=float)
			finite = np.isfinite(x)
			valid_stage = stage_mask & finite
			if np.sum(valid_stage) < 5:
				continue

			stage_vals = x[valid_stage]
			lo = float(np.quantile(stage_vals, interval_q_low))
			hi = float(np.quantile(stage_vals, interval_q_high))
			if not np.isfinite(lo) or not np.isfinite(hi):
				continue

			interval_mask = finite & (x >= lo) & (x <= hi)
			coverage, precision, lift, distinctiveness = _interval_metrics(interval_mask, stage_mask)

			rows.append(
				{
					"stage": int(stage),
					"stage_name": STAGE_NAMES.get(int(stage), f"Stage_{int(stage)}"),
					"feature": str(fname),
					"interval_low": lo,
					"interval_high": hi,
					"coverage": coverage,
					"precision": precision,
					"lift": lift,
					"distinctiveness_index": distinctiveness,
				}
			)

	rows.sort(key=lambda r: (r["stage"], -r["distinctiveness_index"], -r["precision"]))
	for stage in unique_stages:
		stage_rows = [r for r in rows if r["stage"] == stage]
		for rank_idx, row in enumerate(stage_rows, start=1):
			row["rank_within_stage"] = rank_idx

	return rows


def stage_distinctive_feature_combinations(
	features: np.ndarray,
	scores: np.ndarray,
	feature_names: Sequence[str],
	top_features_per_stage: List[Dict[str, float]],
	interval_q_low: float = 0.20,
	interval_q_high: float = 0.80,
	max_pairs_per_stage: int = 12,
) -> List[Dict[str, float]]:
	"""Find stage-indicative two-feature interval combinations.

	Pairs are built from top single-feature candidates per stage and scored by
	how pure and stage-focused the joint interval box is.
	"""
	rows: List[Dict[str, float]] = []
	unique_stages = sorted(int(s) for s in np.unique(scores))
	name_to_idx = {str(n): i for i, n in enumerate(feature_names)}

	for stage in unique_stages:
		stage_mask = np.asarray(scores == stage)
		stage_candidates = [r for r in top_features_per_stage if r["stage"] == stage][:max_pairs_per_stage]
		candidate_names = [r["feature"] for r in stage_candidates if r["feature"] in name_to_idx]
		if len(candidate_names) < 2:
			continue

		for a in range(len(candidate_names)):
			for b in range(a + 1, len(candidate_names)):
				f1 = candidate_names[a]
				f2 = candidate_names[b]
				i1 = name_to_idx[f1]
				i2 = name_to_idx[f2]

				x1 = np.asarray(features[:, i1], dtype=float)
				x2 = np.asarray(features[:, i2], dtype=float)
				finite = np.isfinite(x1) & np.isfinite(x2)
				valid_stage = stage_mask & finite
				if np.sum(valid_stage) < 5:
					continue

				s1 = x1[valid_stage]
				s2 = x2[valid_stage]
				f1_lo = float(np.quantile(s1, interval_q_low))
				f1_hi = float(np.quantile(s1, interval_q_high))
				f2_lo = float(np.quantile(s2, interval_q_low))
				f2_hi = float(np.quantile(s2, interval_q_high))

				joint_mask = (
					finite
					& (x1 >= f1_lo) & (x1 <= f1_hi)
					& (x2 >= f2_lo) & (x2 <= f2_hi)
				)
				coverage, precision, lift, distinctiveness = _interval_metrics(joint_mask, stage_mask)

				rows.append(
					{
						"stage": int(stage),
						"stage_name": STAGE_NAMES.get(int(stage), f"Stage_{int(stage)}"),
						"feature_1": f1,
						"feature_1_low": f1_lo,
						"feature_1_high": f1_hi,
						"feature_2": f2,
						"feature_2_low": f2_lo,
						"feature_2_high": f2_hi,
						"coverage": coverage,
						"precision": precision,
						"lift": lift,
						"distinctiveness_index": distinctiveness,
					}
				)

	rows.sort(key=lambda r: (r["stage"], -r["distinctiveness_index"], -r["precision"]))
	for stage in unique_stages:
		stage_rows = [r for r in rows if r["stage"] == stage]
		for rank_idx, row in enumerate(stage_rows, start=1):
			row["rank_within_stage"] = rank_idx

	return rows


def _add_stage_normalized_distinctiveness(
	rows: List[Dict[str, float]],
	source_key: str = "distinctiveness_index",
	target_key: str = "distinctiveness_index_norm_stage",
) -> List[Dict[str, float]]:
	"""Add per-stage min-max normalization (0-1) for a distinctiveness metric."""
	if not rows:
		return []

	out_rows = [dict(r) for r in rows]
	stages = sorted({int(r["stage"]) for r in out_rows})

	for stage in stages:
		stage_vals = [float(r.get(source_key, np.nan)) for r in out_rows if int(r["stage"]) == stage]
		stage_vals = [v for v in stage_vals if np.isfinite(v)]
		if not stage_vals:
			for r in out_rows:
				if int(r["stage"]) == stage:
					r[target_key] = 0.0
			continue

		vmax = max(stage_vals)
		if not np.isfinite(vmax) or vmax <= 0:
			for r in out_rows:
				if int(r["stage"]) == stage:
					r[target_key] = 0.0
			continue

		for r in out_rows:
			if int(r["stage"]) != stage:
				continue
			v = float(r.get(source_key, np.nan))
			r[target_key] = float(v / vmax) if np.isfinite(v) else 0.0

	return out_rows


def plot_stage_distinctive_intervals(
	interval_rows: List[Dict[str, float]],
	out_path: str,
	top_n_per_stage: int = 3,
	value_key: str = "distinctiveness_index",
	xlabel: str = "Distinctiveness Index",
) -> None:
	"""Plot top stage-indicative single-feature intervals per stage."""
	if not interval_rows:
		return

	stages = sorted({int(r["stage"]) for r in interval_rows})
	n = len(stages)
	n_cols = 2
	n_rows = int(np.ceil(n / n_cols))
	fig, axes = plt.subplots(n_rows, n_cols, figsize=(14, 3.8 * n_rows), squeeze=False)

	for idx, stage in enumerate(stages):
		r = idx // n_cols
		c = idx % n_cols
		ax = axes[r][c]

		rows_stage = [x for x in interval_rows if int(x["stage"]) == stage][:top_n_per_stage]
		if not rows_stage:
			ax.text(0.5, 0.5, "No data", ha="center", va="center", transform=ax.transAxes)
			ax.axis("off")
			continue

		labels = [f"{row['feature']} [{row['interval_low']:.2f}, {row['interval_high']:.2f}]" for row in rows_stage]
		values = [float(row.get(value_key, np.nan)) for row in rows_stage]
		values = [v if np.isfinite(v) else 0.0 for v in values]
		ax.barh(labels[::-1], values[::-1], color="tab:orange", alpha=0.85)
		ax.set_title(f"{STAGE_NAMES.get(stage, f'Stage_{stage}')}: top interval indicators")
		ax.set_xlabel(xlabel)
		ax.tick_params(axis="y", labelsize=8)

	for j in range(n, n_rows * n_cols):
		r = j // n_cols
		c = j % n_cols
		axes[r][c].axis("off")

	fig.tight_layout()
	fig.savefig(out_path, dpi=220)
	plt.close(fig)


def _write_csv(path: str, rows: List[Dict[str, float]], columns: Sequence[str]) -> None:
	with open(path, "w", newline="", encoding="utf-8") as f:
		writer = csv.DictWriter(f, fieldnames=list(columns))
		writer.writeheader()
		for row in rows:
			writer.writerow(row)


def _sanitize_name(name: str) -> str:
	safe = "".join(ch if ch.isalnum() or ch in ("-", "_") else "_" for ch in name)
	return safe.strip("_") or "feature"


def plot_stage_distribution(scores: np.ndarray, out_path: str) -> None:
	stages, counts = np.unique(scores, return_counts=True)
	labels = [STAGE_NAMES.get(int(s), f"Stage_{int(s)}") for s in stages]

	fig, ax = plt.subplots(figsize=(8, 4.5))
	ax.bar(labels, counts)
	ax.set_title("Epoch Count per Sleep Stage")
	ax.set_ylabel("Number of Epochs")
	ax.tick_params(axis="x", rotation=20)
	fig.tight_layout()
	fig.savefig(out_path, dpi=200)
	plt.close(fig)


def plot_correlation_heatmap(features: np.ndarray, feature_names: Sequence[str], out_path: str) -> None:
	corr = _safe_correlation_matrix(features)

	fig, ax = plt.subplots(figsize=(11, 9))
	im = ax.imshow(corr, cmap="coolwarm", vmin=-1.0, vmax=1.0)
	ax.set_xticks(np.arange(len(feature_names)))
	ax.set_yticks(np.arange(len(feature_names)))
	ax.set_xticklabels(feature_names, rotation=45, ha="right")
	ax.set_yticklabels(feature_names)
	ax.set_title("Feature Correlation Matrix")
	fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="Pearson r")
	fig.tight_layout()
	fig.savefig(out_path, dpi=220)
	plt.close(fig)


def _safe_correlation_matrix(features: np.ndarray) -> np.ndarray:
	x = np.asarray(features, dtype=float)
	with warnings.catch_warnings():
		warnings.simplefilter("ignore", RuntimeWarning)
		corr = np.corrcoef(x, rowvar=False)

	if corr.ndim == 0:
		corr = np.array([[1.0]])

	# Constant features create undefined correlations (NaN); set those to 0 off-diagonal.
	corr = np.where(np.isfinite(corr), corr, 0.0)
	n = corr.shape[0]
	for i in range(n):
		corr[i, i] = 1.0
	return corr


def plot_feature_by_stage(
	features: np.ndarray,
	scores: np.ndarray,
	feature_names: Sequence[str],
	out_dir: str,
) -> None:
	unique_stages = sorted(int(s) for s in np.unique(scores))
	stage_labels = [STAGE_NAMES.get(s, f"Stage_{s}") for s in unique_stages]

	for i, feature_name in enumerate(feature_names):
		data = [features[scores == s, i] for s in unique_stages]
		data = [d[np.isfinite(d)] for d in data]

		fig, ax = plt.subplots(figsize=(9.5, 4.8))
		ax.violinplot(data, showmeans=True, showextrema=True)
		ax.set_xticks(np.arange(1, len(stage_labels) + 1))
		ax.set_xticklabels(stage_labels, rotation=20)
		ax.set_ylabel("Feature Value")
		ax.set_title(f"{feature_name}: Distribution Across Sleep Stages")
		fig.tight_layout()
		fig.savefig(os.path.join(out_dir, f"{_sanitize_name(feature_name)}_violin.png"), dpi=200)
		plt.close(fig)


def plot_all_feature_violins_overview(
	features: np.ndarray,
	scores: np.ndarray,
	feature_names: Sequence[str],
	out_path: str,
) -> None:
	"""Create one overview figure containing violin plots for all features."""
	unique_stages = sorted(int(s) for s in np.unique(scores))
	stage_labels = [STAGE_NAMES.get(s, f"Stage_{s}") for s in unique_stages]

	n_features = len(feature_names)
	n_cols = 3
	n_rows = int(np.ceil(n_features / n_cols))
	fig, axes = plt.subplots(n_rows, n_cols, figsize=(18, 4.4 * n_rows), squeeze=False)

	for i, feature_name in enumerate(feature_names):
		r = i // n_cols
		c = i % n_cols
		ax = axes[r][c]

		data = [features[scores == s, i] for s in unique_stages]
		data = [d[np.isfinite(d)] for d in data]
		if any(d.size > 0 for d in data):
			ax.violinplot(data, showmeans=True, showextrema=True)
			ax.set_xticks(np.arange(1, len(stage_labels) + 1))
			ax.set_xticklabels(stage_labels, rotation=20, fontsize=8)
		else:
			ax.text(0.5, 0.5, "No valid data", ha="center", va="center", transform=ax.transAxes)
			ax.set_xticks([])

		ax.set_title(feature_name, fontsize=10)
		ax.set_ylabel("Value", fontsize=8)

	# Hide unused axes when feature count is not a multiple of n_cols.
	for j in range(n_features, n_rows * n_cols):
		r = j // n_cols
		c = j % n_cols
		axes[r][c].axis("off")

	fig.suptitle("All Features: Violin Distributions Across Sleep Stages", fontsize=14)
	fig.tight_layout(rect=(0, 0, 1, 0.98))
	fig.savefig(out_path, dpi=220)
	plt.close(fig)


def plot_feature_histograms(
	features: np.ndarray,
	scores: np.ndarray,
	feature_names: Sequence[str],
	out_dir: str,
) -> None:
	unique_stages = sorted(int(s) for s in np.unique(scores))
	stage_labels = [STAGE_NAMES.get(s, f"Stage_{s}") for s in unique_stages]

	for i, feature_name in enumerate(feature_names):
		fig, ax = plt.subplots(figsize=(9.5, 4.8))
		for stage, label in zip(unique_stages, stage_labels):
			vals = features[scores == stage, i]
			vals = vals[np.isfinite(vals)]
			if vals.size == 0:
				continue
			ax.hist(vals, bins=40, alpha=0.35, density=True, label=label)

		ax.set_title(f"{feature_name}: Overlapping Histograms by Stage")
		ax.set_xlabel("Feature Value")
		ax.set_ylabel("Density")
		ax.legend(loc="best", fontsize=8)
		fig.tight_layout()
		fig.savefig(os.path.join(out_dir, f"{_sanitize_name(feature_name)}_hist.png"), dpi=200)
		plt.close(fig)


def _downsample_for_plot(
	features: np.ndarray,
	scores: np.ndarray,
	max_points: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
	"""Downsample epochs for plotting to keep figures responsive."""
	n = len(scores)
	if n == 0:
		return np.array([], dtype=int), features, scores

	if max_points <= 0 or n <= max_points:
		x = np.arange(n)
		return x, features, scores

	stride = int(np.ceil(n / max_points))
	indices = np.arange(0, n, stride)
	return indices, features[indices], scores[indices]


def _downsample_stage_values(stage_values: np.ndarray, max_points: int) -> tuple[np.ndarray, np.ndarray]:
	"""Downsample a stage trace while preserving transitions for plotting."""
	n = len(stage_values)
	if n == 0:
		return np.array([], dtype=int), np.array([], dtype=int)

	if max_points <= 0 or n <= max_points:
		return np.arange(n), stage_values

	stride = int(np.ceil(n / max_points))
	indices = np.arange(0, n, stride)
	return indices, stage_values[indices]


def _find_feature_index(feature_names: Sequence[str], target: str) -> int:
	"""Find feature index by normalized name; returns -1 if not found."""
	norm_target = target.lower().replace(" ", "").replace("-", "").replace("_", "")
	for i, name in enumerate(feature_names):
		norm_name = str(name).lower().replace(" ", "").replace("-", "").replace("_", "")
		if norm_name == norm_target:
			return i
	return -1


def _find_first_feature_index(feature_names: Sequence[str], candidates: Sequence[str]) -> int:
	"""Return first matching feature index from candidate names, else -1."""
	for candidate in candidates:
		idx = _find_feature_index(feature_names, candidate)
		if idx >= 0:
			return idx
	return -1


def derive_stage_trace_from_features(
	features: np.ndarray,
	feature_names: Sequence[str],
	fallback_scores: np.ndarray,
) -> np.ndarray:
	"""
	Build stage transitions from feature indices.

	Rules:
	- Wake = Index_W
	- NREM = Index_N, then subtype via max(Index_1, Index_2, Index_3) -> N1/N2/N3
	- REM = Index_R
	"""
	idx_w = _find_first_feature_index(feature_names, ["Index_W"])
	idx_n = _find_first_feature_index(feature_names, ["Index_N", "Index_N_EOG", "Index_N_noEOG"])
	idx_r = _find_first_feature_index(feature_names, ["Index_R", "Index_R_EOG", "Index_R_noEOG"])
	idx_1 = _find_feature_index(feature_names, "Index_1")
	idx_2 = _find_feature_index(feature_names, "Index_2")
	idx_3 = _find_feature_index(feature_names, "Index_3")

	required = [idx_w, idx_n, idx_r, idx_1, idx_2, idx_3]
	if any(i < 0 for i in required):
		return fallback_scores

	n = features.shape[0]
	derived = np.zeros(n, dtype=int)

	broad = np.column_stack(
		[
			np.nan_to_num(features[:, idx_w], nan=-np.inf),
			np.nan_to_num(features[:, idx_n], nan=-np.inf),
			np.nan_to_num(features[:, idx_r], nan=-np.inf),
		]
	)
	broad_choice = np.argmax(broad, axis=1)

	# 0 -> Wake, 1 -> NREM, 2 -> REM
	derived[broad_choice == 0] = 0
	derived[broad_choice == 2] = 4

	nrem_mask = broad_choice == 1
	if np.any(nrem_mask):
		nrem_sub = np.column_stack(
			[
				np.nan_to_num(features[nrem_mask, idx_1], nan=-np.inf),
				np.nan_to_num(features[nrem_mask, idx_2], nan=-np.inf),
				np.nan_to_num(features[nrem_mask, idx_3], nan=-np.inf),
			]
		)
		sub_choice = np.argmax(nrem_sub, axis=1)
		# 0->N1 (1), 1->N2 (2), 2->N3 (3)
		derived[nrem_mask] = sub_choice + 1

	return derived


def _plot_single_hypnogram(
	x: np.ndarray,
	feature_values: np.ndarray,
	stage_values: np.ndarray,
	feature_name: str,
	out_path: str,
) -> None:
	"""Plot one feature trace with corresponding hypnogram (stage trace)."""
	fig, (ax_feat, ax_stage) = plt.subplots(
		2,
		1,
		figsize=(12, 5.8),
		sharex=True,
		gridspec_kw={"height_ratios": [2.7, 1.3]},
	)

	valid = np.isfinite(feature_values)
	ax_feat.plot(x[valid], feature_values[valid], linewidth=0.7)
	ax_feat.set_ylabel("Feature value")
	ax_feat.set_title(f"{feature_name}: Feature Trace + Hypnogram")
	ax_feat.grid(alpha=0.25)

	stages_unique = sorted(int(s) for s in np.unique(stage_values))
	stage_levels = np.asarray(stage_values, dtype=float)
	ax_stage.step(x, stage_levels, where="post", linewidth=1.1, color="black")
	ax_stage.set_yticks(stages_unique)
	ax_stage.set_yticklabels([STAGE_NAMES.get(s, f"Stage_{s}") for s in stages_unique])
	ax_stage.invert_yaxis()
	ax_stage.set_ylabel("Stage")
	ax_stage.set_xlabel("Epoch index")
	ax_stage.grid(alpha=0.25)

	fig.tight_layout()
	fig.savefig(out_path, dpi=220)
	plt.close(fig)


def plot_stage_hypnogram(
	stage_values: np.ndarray,
	out_path: str,
	title: str,
	max_points: int = 25000,
) -> None:
	"""Plot a stage-only hypnogram line."""
	x, stage_plot = _downsample_stage_values(np.asarray(stage_values, dtype=int), max_points=max_points)
	if len(stage_plot) == 0:
		return

	stages_unique = sorted(int(s) for s in np.unique(stage_plot))
	fig, ax = plt.subplots(figsize=(13, 3.8))
	ax.step(x, stage_plot.astype(float), where="post", linewidth=1.0, color="black")
	ax.set_yticks(stages_unique)
	ax.set_yticklabels([STAGE_NAMES.get(s, f"Stage_{s}") for s in stages_unique])
	ax.invert_yaxis()
	ax.set_xlabel("Epoch index")
	ax.set_ylabel("Stage")
	ax.set_title(title)
	ax.grid(alpha=0.25)
	fig.tight_layout()
	fig.savefig(out_path, dpi=220)
	plt.close(fig)


def _most_common_stage_per_epoch(stage_sequences: List[np.ndarray]) -> np.ndarray:
	"""Compute consensus stage by epoch index across subjects."""
	if not stage_sequences:
		return np.array([], dtype=int)

	max_len = max(len(seq) for seq in stage_sequences)
	consensus = np.zeros(max_len, dtype=int)

	for epoch_idx in range(max_len):
		values = [int(seq[epoch_idx]) for seq in stage_sequences if epoch_idx < len(seq)]
		if not values:
			consensus[epoch_idx] = 0
			continue

		arr = np.asarray(values, dtype=int)
		arr = arr[arr >= 0]
		if arr.size == 0:
			consensus[epoch_idx] = 0
			continue

		counts = np.bincount(arr)
		consensus[epoch_idx] = int(np.argmax(counts))

	return consensus


def plot_subject_and_consensus_hypnograms(
	subject_data: List[SubjectData],
	feature_names: Sequence[str],
	output_dir: str,
	use_feature_derived: bool = False,
) -> None:
	"""Save one hypnogram per subject and one epoch-wise consensus hypnogram.

	By default this uses true scored labels from HDF5. Set
	`use_feature_derived=True` to use feature-derived stage transitions.
	"""
	if use_feature_derived:
		subject_dir = os.path.join(output_dir, "subject_hypnograms_feature_derived")
		consensus_png = "hypnogram_consensus_feature_derived_most_common_stage_per_epoch.png"
		consensus_csv = "hypnogram_consensus_feature_derived_per_epoch.csv"
		title_suffix = "feature-derived stage transitions"
	else:
		subject_dir = os.path.join(output_dir, "subject_hypnograms")
		consensus_png = "hypnogram_consensus_most_common_stage_per_epoch.png"
		consensus_csv = "hypnogram_consensus_per_epoch.csv"
		title_suffix = "true scored stages"
	os.makedirs(subject_dir, exist_ok=True)

	stage_sequences: List[np.ndarray] = []
	consensus_rows: List[Dict[str, float]] = []

	for subj in subject_data:
		if use_feature_derived:
			stage_values = derive_stage_trace_from_features(subj.features, feature_names, subj.scores)
		else:
			stage_values = np.asarray(subj.scores, dtype=int)

		stage_sequences.append(stage_values)
		plot_stage_hypnogram(
			stage_values=stage_values,
			out_path=os.path.join(subject_dir, f"hypnogram_{_sanitize_name(subj.subject)}.png"),
			title=f"Hypnogram ({subj.subject}) - {title_suffix}",
		)

	consensus = _most_common_stage_per_epoch(stage_sequences)
	plot_stage_hypnogram(
		stage_values=consensus,
		out_path=os.path.join(output_dir, consensus_png),
		title="Consensus Hypnogram - most common stage per epoch index",
	)

	for epoch_idx, stage in enumerate(consensus):
		n_subjects = int(sum(1 for seq in stage_sequences if epoch_idx < len(seq)))
		consensus_rows.append(
			{
				"epoch": epoch_idx,
				"consensus_stage": int(stage),
				"consensus_stage_name": STAGE_NAMES.get(int(stage), f"Stage_{int(stage)}"),
				"n_subjects_contributing": n_subjects,
			}
		)

	_write_csv(
		path=os.path.join(output_dir, consensus_csv),
		rows=consensus_rows,
		columns=["epoch", "consensus_stage", "consensus_stage_name", "n_subjects_contributing"],
	)


def plot_feature_hypnograms(
	features: np.ndarray,
	scores: np.ndarray,
	feature_names: Sequence[str],
	out_dir: str,
	max_points: int = 20000,
) -> None:
	"""Save one hypnogram-style plot per feature."""
	x, features_plot, scores_plot = _downsample_for_plot(features, scores, max_points=max_points)

	for i, feature_name in enumerate(feature_names):
		out_path = os.path.join(out_dir, f"{_sanitize_name(feature_name)}_hypnogram.png")
		_plot_single_hypnogram(
			x=x,
			feature_values=features_plot[:, i],
			stage_values=scores_plot,
			feature_name=feature_name,
			out_path=out_path,
		)


def plot_all_feature_hypnograms_overview(
	features: np.ndarray,
	scores: np.ndarray,
	feature_names: Sequence[str],
	out_path: str,
	max_points: int = 15000,
) -> None:
	"""Create one overview figure containing hypnogram-style panels for all features."""
	x, features_plot, scores_plot = _downsample_for_plot(features, scores, max_points=max_points)
	stages_unique = sorted(int(s) for s in np.unique(scores_plot))

	n_features = len(feature_names)
	n_cols = 2
	n_rows = int(np.ceil(n_features / n_cols))
	fig, axes = plt.subplots(n_rows, n_cols, figsize=(18, 3.6 * n_rows), squeeze=False)

	for i, feature_name in enumerate(feature_names):
		r = i // n_cols
		c = i % n_cols
		ax = axes[r][c]

		series = features_plot[:, i]
		valid = np.isfinite(series)
		ax.plot(x[valid], series[valid], linewidth=0.6, color="tab:blue", alpha=0.9)

		# Overlay stage trace on a twin y-axis to keep both views in one panel.
		ax_stage = ax.twinx()
		ax_stage.step(x, scores_plot.astype(float), where="post", linewidth=0.8, color="black", alpha=0.55)
		ax_stage.set_yticks(stages_unique)
		ax_stage.set_yticklabels([str(s) for s in stages_unique], fontsize=7)
		ax_stage.invert_yaxis()

		ax.set_title(feature_name, fontsize=10)
		ax.set_ylabel("Value", fontsize=8)
		ax.tick_params(axis="both", labelsize=8)
		ax.grid(alpha=0.2)

		if r == n_rows - 1:
			ax.set_xlabel("Epoch index", fontsize=8)

	# Hide unused axes when feature count is not a multiple of n_cols.
	for j in range(n_features, n_rows * n_cols):
		r = j // n_cols
		c = j % n_cols
		axes[r][c].axis("off")

	fig.suptitle("All Features: Hypnogram Overview (feature trace + stage trace)", fontsize=14)
	fig.tight_layout(rect=(0, 0, 1, 0.98))
	fig.savefig(out_path, dpi=220)
	plt.close(fig)


def _plot_single_pca_projection(
	x_pca: np.ndarray,
	scores: np.ndarray,
	explained_variance_ratio: np.ndarray,
	component_x: int,
	component_y: int,
	out_path: str,
) -> None:
	"""Plot one pair of principal components (1-indexed component labels)."""
	ix = component_x - 1
	iy = component_y - 1

	fig, ax = plt.subplots(figsize=(8.5, 6.0))
	unique_stages = sorted(int(s) for s in np.unique(scores))
	for stage in unique_stages:
		mask = scores == stage
		ax.scatter(
			x_pca[mask, ix],
			x_pca[mask, iy],
			s=12,
			alpha=0.55,
			label=STAGE_NAMES.get(stage, f"Stage_{stage}"),
		)

	ax.set_xlabel(f"PC{component_x} ({explained_variance_ratio[ix] * 100:.1f}% var)")
	ax.set_ylabel(f"PC{component_y} ({explained_variance_ratio[iy] * 100:.1f}% var)")
	ax.set_title(f"PCA Projection: PC{component_x} vs PC{component_y}")
	ax.legend(loc="best", fontsize=8)
	fig.tight_layout()
	fig.savefig(out_path, dpi=220)
	plt.close(fig)


def plot_pca_projections(features: np.ndarray, scores: np.ndarray, output_dir: str) -> None:
	"""Save PCA projections for PC1-2, PC1-3, and PC2-3."""
	scaler = StandardScaler()
	x_scaled = scaler.fit_transform(features)

	n_components = min(3, x_scaled.shape[1])
	pca = PCA(n_components=n_components, random_state=42)
	x_pca = pca.fit_transform(x_scaled)
	ev_ratio = pca.explained_variance_ratio_

	# Always save PC1 vs PC2 when available.
	if n_components >= 2:
		_plot_single_pca_projection(
			x_pca,
			scores,
			ev_ratio,
			component_x=1,
			component_y=2,
			out_path=os.path.join(output_dir, "feature_space_pca_pc1_pc2.png"),
		)

	# Save additional overview projections when PC3 exists.
	if n_components >= 3:
		_plot_single_pca_projection(
			x_pca,
			scores,
			ev_ratio,
			component_x=1,
			component_y=3,
			out_path=os.path.join(output_dir, "feature_space_pca_pc1_pc3.png"),
		)
		_plot_single_pca_projection(
			x_pca,
			scores,
			ev_ratio,
			component_x=2,
			component_y=3,
			out_path=os.path.join(output_dir, "feature_space_pca_pc2_pc3.png"),
		)



def plot_feature_ranking(ranked_rows: List[Dict[str, float]], out_path: str, top_n: int = 13) -> None:
	top_rows = ranked_rows[:top_n]
	labels = [r["feature"] for r in top_rows]
	scores = [r["selection_score"] for r in top_rows]

	fig, ax = plt.subplots(figsize=(9.0, 5.2))
	ax.barh(labels[::-1], scores[::-1])
	ax.set_xlabel("Composite Selection Score")
	ax.set_title(f"Top {len(top_rows)} Candidate Features for mcRBM")
	fig.tight_layout()
	fig.savefig(out_path, dpi=220)
	plt.close(fig)


def plot_stage_specificity_ranking(
	ranked_rows: List[Dict[str, float]],
	out_path: str,
	top_n: int = 13,
) -> None:
	"""Plot ranking based on stage specificity score."""
	top_rows = ranked_rows[:top_n]
	labels = [f"{r['feature']} ({r['most_specific_stage_name']})" for r in top_rows]
	scores = [r["stage_specificity_score"] for r in top_rows]

	fig, ax = plt.subplots(figsize=(11.0, 6.0))
	ax.barh(labels[::-1], scores[::-1], color="tab:green", alpha=0.85)
	ax.set_xlabel("Stage Specificity Score")
	ax.set_title(f"Top {len(top_rows)} Features by Stage Specificity")
	fig.tight_layout()
	fig.savefig(out_path, dpi=220)
	plt.close(fig)


def run_analysis(hdf5_path: str, output_dir: str, include_artifacts: bool = False) -> None:
	os.makedirs(output_dir, exist_ok=True)
	per_feature_dir = os.path.join(output_dir, "per_feature")
	os.makedirs(per_feature_dir, exist_ok=True)

	data = load_hdf5_features(hdf5_path=hdf5_path, include_artifacts=include_artifacts)
	subject_data, subject_feature_names = load_hdf5_subject_data(
		hdf5_path=hdf5_path,
		include_artifacts=include_artifacts,
	)

	basic_stats = feature_basic_statistics(data.features, data.feature_names)
	stage_stats = feature_stage_statistics(data.features, data.scores, data.feature_names)
	disc_metrics = discriminative_feature_metrics(data.features, data.scores, data.feature_names)
	ranked = rank_features(disc_metrics)
	stage_specific_rows = stage_specificity_metrics(data.features, data.scores, data.feature_names)
	stage_specific_ranked = rank_features_by_stage_specificity(stage_specific_rows)
	stage_interval_rows = stage_distinctive_feature_intervals(
		data.features,
		data.scores,
		data.feature_names,
	)
	stage_combo_rows = stage_distinctive_feature_combinations(
		data.features,
		data.scores,
		data.feature_names,
		stage_interval_rows,
	)
	stage_interval_rows_norm = _add_stage_normalized_distinctiveness(stage_interval_rows)
	stage_combo_rows_norm = _add_stage_normalized_distinctiveness(stage_combo_rows)

	_write_csv(
		path=os.path.join(output_dir, "feature_basic_stats.csv"),
		rows=basic_stats,
		columns=[
			"feature",
			"n",
			"mean",
			"std",
			"median",
			"q25",
			"q75",
			"iqr",
			"min",
			"max",
			"skew",
			"kurtosis",
			"is_constant",
			"outlier_pct",
		],
	)

	_write_csv(
		path=os.path.join(output_dir, "feature_stage_stats.csv"),
		rows=stage_stats,
		columns=[
			"feature",
			"stage",
			"stage_name",
			"n",
			"mean",
			"std",
			"median",
			"q25",
			"q75",
			"iqr",
			"min",
			"max",
			"skew",
			"kurtosis",
			"is_constant",
			"outlier_pct",
		],
	)

	_write_csv(
		path=os.path.join(output_dir, "feature_discriminative_metrics.csv"),
		rows=disc_metrics,
		columns=[
			"feature",
			"mutual_info",
			"fisher_score",
			"eta_squared",
			"is_constant",
			"anova_f",
			"anova_p",
			"kruskal_h",
			"kruskal_p",
		],
	)

	_write_csv(
		path=os.path.join(output_dir, "feature_ranking.csv"),
		rows=ranked,
		columns=[
			"rank",
			"feature",
			"selection_score",
			"mutual_info",
			"fisher_score",
			"eta_squared",
			"is_constant",
			"anova_f",
			"anova_p",
			"kruskal_h",
			"kruskal_p",
		],
	)

	_write_csv(
		path=os.path.join(output_dir, "feature_stage_specificity_ranking.csv"),
		rows=stage_specific_ranked,
		columns=[
			"rank",
			"feature",
			"most_specific_stage",
			"most_specific_stage_name",
			"stage_specificity_score",
			"max_one_vs_rest_effect",
			"effect_margin",
			"stage_mean_concentration",
		],
	)

	_write_csv(
		path=os.path.join(output_dir, "stage_distinct_feature_intervals.csv"),
		rows=stage_interval_rows,
		columns=[
			"stage",
			"stage_name",
			"rank_within_stage",
			"feature",
			"interval_low",
			"interval_high",
			"coverage",
			"precision",
			"lift",
			"distinctiveness_index",
		],
	)

	_write_csv(
		path=os.path.join(output_dir, "stage_distinct_feature_intervals_normalized.csv"),
		rows=stage_interval_rows_norm,
		columns=[
			"stage",
			"stage_name",
			"rank_within_stage",
			"feature",
			"interval_low",
			"interval_high",
			"coverage",
			"precision",
			"lift",
			"distinctiveness_index",
			"distinctiveness_index_norm_stage",
		],
	)

	_write_csv(
		path=os.path.join(output_dir, "stage_distinct_feature_combinations.csv"),
		rows=stage_combo_rows,
		columns=[
			"stage",
			"stage_name",
			"rank_within_stage",
			"feature_1",
			"feature_1_low",
			"feature_1_high",
			"feature_2",
			"feature_2_low",
			"feature_2_high",
			"coverage",
			"precision",
			"lift",
			"distinctiveness_index",
		],
	)

	_write_csv(
		path=os.path.join(output_dir, "stage_distinct_feature_combinations_normalized.csv"),
		rows=stage_combo_rows_norm,
		columns=[
			"stage",
			"stage_name",
			"rank_within_stage",
			"feature_1",
			"feature_1_low",
			"feature_1_high",
			"feature_2",
			"feature_2_low",
			"feature_2_high",
			"coverage",
			"precision",
			"lift",
			"distinctiveness_index",
			"distinctiveness_index_norm_stage",
		],
	)

	# Save matrix for external analysis.
	corr = _safe_correlation_matrix(data.features)
	np.savetxt(
		fname=os.path.join(output_dir, "feature_correlation_matrix.csv"),
		X=corr,
		delimiter=",",
		header=",".join(data.feature_names),
		comments="",
	)

	plot_stage_distribution(data.scores, os.path.join(output_dir, "stage_distribution.png"))
	plot_correlation_heatmap(
		data.features,
		data.feature_names,
		os.path.join(output_dir, "feature_correlation_heatmap.png"),
	)
	plot_pca_projections(data.features, data.scores, output_dir)
	plot_feature_ranking(ranked, os.path.join(output_dir, "feature_ranking.png"), top_n=len(data.feature_names))
	plot_stage_specificity_ranking(
		stage_specific_ranked,
		os.path.join(output_dir, "feature_stage_specificity_ranking.png"),
		top_n=len(data.feature_names),
	)
	plot_stage_distinctive_intervals(
		stage_interval_rows,
		os.path.join(output_dir, "stage_distinct_feature_intervals.png"),
		top_n_per_stage=3,
	)
	plot_stage_distinctive_intervals(
		stage_interval_rows_norm,
		os.path.join(output_dir, "stage_distinct_feature_intervals_normalized.png"),
		top_n_per_stage=3,
		value_key="distinctiveness_index_norm_stage",
		xlabel="Distinctiveness Index (Stage-normalized 0-1)",
	)
	plot_feature_by_stage(data.features, data.scores, data.feature_names, per_feature_dir)
	plot_all_feature_violins_overview(
		data.features,
		data.scores,
		data.feature_names,
		os.path.join(output_dir, "all_features_violin_overview.png"),
	)
	plot_feature_histograms(data.features, data.scores, data.feature_names, per_feature_dir)
	# Main hypnogram overlays use true scored labels.
	plot_feature_hypnograms(data.features, data.scores, data.feature_names, per_feature_dir)
	plot_all_feature_hypnograms_overview(
		data.features,
		data.scores,
		data.feature_names,
		os.path.join(output_dir, "all_features_hypnogram_overview.png"),
	)

	# Keep feature-derived hypnograms as optional diagnostics.
	derived_hypnogram_scores = derive_stage_trace_from_features(data.features, data.feature_names, data.scores)
	derived_dir = os.path.join(per_feature_dir, "feature_derived_hypnograms")
	os.makedirs(derived_dir, exist_ok=True)
	plot_feature_hypnograms(data.features, derived_hypnogram_scores, data.feature_names, derived_dir)
	plot_all_feature_hypnograms_overview(
		data.features,
		derived_hypnogram_scores,
		data.feature_names,
		os.path.join(output_dir, "all_features_hypnogram_overview_feature_derived.png"),
	)

	plot_subject_and_consensus_hypnograms(
		subject_data=subject_data,
		feature_names=subject_feature_names,
		output_dir=output_dir,
		use_feature_derived=False,
	)
	plot_subject_and_consensus_hypnograms(
		subject_data=subject_data,
		feature_names=subject_feature_names,
		output_dir=output_dir,
		use_feature_derived=True,
	)

	print("Analysis complete")
	print(f"Input HDF5      : {hdf5_path}")
	print(f"Total epochs    : {len(data.scores)}")
	print(f"Total features  : {len(data.feature_names)}")
	print(f"Output directory: {output_dir}")
	print("Top 5 features by composite selection score:")
	for row in ranked[:5]:
		print(
			f"  {row['rank']:>2}. {row['feature']:<15} "
			f"score={row['selection_score']:.3f} "
			f"MI={row['mutual_info']:.3f} eta2={row['eta_squared']:.3f}"
		)


def build_parser() -> argparse.ArgumentParser:
	parser = argparse.ArgumentParser(
		description="Compute feature statistics/plots from Jalmar sleep HDF5 for mcRBM feature selection."
	)
	parser.add_argument("--hdf5", required=True, help="Path to HDF5 file with subject groups/features/scores.")
	parser.add_argument(
		"--output_dir",
		default="feature_stats_output",
		help="Directory where CSV files and plots will be saved.",
	)
	parser.add_argument(
		"--include_artifacts",
		action="store_true",
		help="Include stage 5 (Movement/Artifact) epochs in analysis.",
	)
	return parser


def main() -> None:
	parser = build_parser()
	args = parser.parse_args()
	run_analysis(
		hdf5_path=args.hdf5,
		output_dir=args.output_dir,
		include_artifacts=args.include_artifacts,
	)


if __name__ == "__main__":
	main()
